(cl:defpackage probot_ocr-srv
  (:use )
  (:export
   "DETECTOBJECTIONSRV"
   "<DETECTOBJECTIONSRV-REQUEST>"
   "DETECTOBJECTIONSRV-REQUEST"
   "<DETECTOBJECTIONSRV-RESPONSE>"
   "DETECTOBJECTIONSRV-RESPONSE"
  ))

