(cl:defpackage probot_vision-srv
  (:use )
  (:export
   "DETECTOBJECTSRV"
   "<DETECTOBJECTSRV-REQUEST>"
   "DETECTOBJECTSRV-REQUEST"
   "<DETECTOBJECTSRV-RESPONSE>"
   "DETECTOBJECTSRV-RESPONSE"
  ))

