// Generated by gencpp from file probot_vision/DetectObjectSrv.msg
// DO NOT EDIT!


#ifndef PROBOT_VISION_MESSAGE_DETECTOBJECTSRV_H
#define PROBOT_VISION_MESSAGE_DETECTOBJECTSRV_H

#include <ros/service_traits.h>


#include <probot_vision/DetectObjectSrvRequest.h>
#include <probot_vision/DetectObjectSrvResponse.h>


namespace probot_vision
{

struct DetectObjectSrv
{

typedef DetectObjectSrvRequest Request;
typedef DetectObjectSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectObjectSrv
} // namespace probot_vision


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::probot_vision::DetectObjectSrv > {
  static const char* value()
  {
    return "850802356f5638bc276421b4259ada17";
  }

  static const char* value(const ::probot_vision::DetectObjectSrv&) { return value(); }
};

template<>
struct DataType< ::probot_vision::DetectObjectSrv > {
  static const char* value()
  {
    return "probot_vision/DetectObjectSrv";
  }

  static const char* value(const ::probot_vision::DetectObjectSrv&) { return value(); }
};


// service_traits::MD5Sum< ::probot_vision::DetectObjectSrvRequest> should match 
// service_traits::MD5Sum< ::probot_vision::DetectObjectSrv > 
template<>
struct MD5Sum< ::probot_vision::DetectObjectSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::probot_vision::DetectObjectSrv >::value();
  }
  static const char* value(const ::probot_vision::DetectObjectSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_vision::DetectObjectSrvRequest> should match 
// service_traits::DataType< ::probot_vision::DetectObjectSrv > 
template<>
struct DataType< ::probot_vision::DetectObjectSrvRequest>
{
  static const char* value()
  {
    return DataType< ::probot_vision::DetectObjectSrv >::value();
  }
  static const char* value(const ::probot_vision::DetectObjectSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::probot_vision::DetectObjectSrvResponse> should match 
// service_traits::MD5Sum< ::probot_vision::DetectObjectSrv > 
template<>
struct MD5Sum< ::probot_vision::DetectObjectSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::probot_vision::DetectObjectSrv >::value();
  }
  static const char* value(const ::probot_vision::DetectObjectSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_vision::DetectObjectSrvResponse> should match 
// service_traits::DataType< ::probot_vision::DetectObjectSrv > 
template<>
struct DataType< ::probot_vision::DetectObjectSrvResponse>
{
  static const char* value()
  {
    return DataType< ::probot_vision::DetectObjectSrv >::value();
  }
  static const char* value(const ::probot_vision::DetectObjectSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROBOT_VISION_MESSAGE_DETECTOBJECTSRV_H
