// Generated by gencpp from file probot_ocr/detectobjectionSrv.msg
// DO NOT EDIT!


#ifndef PROBOT_OCR_MESSAGE_DETECTOBJECTIONSRV_H
#define PROBOT_OCR_MESSAGE_DETECTOBJECTIONSRV_H

#include <ros/service_traits.h>


#include <probot_ocr/detectobjectionSrvRequest.h>
#include <probot_ocr/detectobjectionSrvResponse.h>


namespace probot_ocr
{

struct detectobjectionSrv
{

typedef detectobjectionSrvRequest Request;
typedef detectobjectionSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct detectobjectionSrv
} // namespace probot_ocr


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::probot_ocr::detectobjectionSrv > {
  static const char* value()
  {
    return "a2a0fbc7168d9342cca042cb3bffafc3";
  }

  static const char* value(const ::probot_ocr::detectobjectionSrv&) { return value(); }
};

template<>
struct DataType< ::probot_ocr::detectobjectionSrv > {
  static const char* value()
  {
    return "probot_ocr/detectobjectionSrv";
  }

  static const char* value(const ::probot_ocr::detectobjectionSrv&) { return value(); }
};


// service_traits::MD5Sum< ::probot_ocr::detectobjectionSrvRequest> should match 
// service_traits::MD5Sum< ::probot_ocr::detectobjectionSrv > 
template<>
struct MD5Sum< ::probot_ocr::detectobjectionSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::probot_ocr::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_ocr::detectobjectionSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_ocr::detectobjectionSrvRequest> should match 
// service_traits::DataType< ::probot_ocr::detectobjectionSrv > 
template<>
struct DataType< ::probot_ocr::detectobjectionSrvRequest>
{
  static const char* value()
  {
    return DataType< ::probot_ocr::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_ocr::detectobjectionSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::probot_ocr::detectobjectionSrvResponse> should match 
// service_traits::MD5Sum< ::probot_ocr::detectobjectionSrv > 
template<>
struct MD5Sum< ::probot_ocr::detectobjectionSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::probot_ocr::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_ocr::detectobjectionSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_ocr::detectobjectionSrvResponse> should match 
// service_traits::DataType< ::probot_ocr::detectobjectionSrv > 
template<>
struct DataType< ::probot_ocr::detectobjectionSrvResponse>
{
  static const char* value()
  {
    return DataType< ::probot_ocr::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_ocr::detectobjectionSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROBOT_OCR_MESSAGE_DETECTOBJECTIONSRV_H
