// Generated by gencpp from file probot_ocr/detectobjectionSrvResponse.msg
// DO NOT EDIT!


#ifndef PROBOT_OCR_MESSAGE_DETECTOBJECTIONSRVRESPONSE_H
#define PROBOT_OCR_MESSAGE_DETECTOBJECTIONSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace probot_ocr
{
template <class ContainerAllocator>
struct detectobjectionSrvResponse_
{
  typedef detectobjectionSrvResponse_<ContainerAllocator> Type;

  detectobjectionSrvResponse_()
    : result(0)
    , charObjList()
    , charName()
    , charNum()
    , angle()  {
    }
  detectobjectionSrvResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , charObjList(_alloc)
    , charName(_alloc)
    , charNum(_alloc)
    , angle(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _charObjList_type;
  _charObjList_type charObjList;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _charName_type;
  _charName_type charName;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _charNum_type;
  _charNum_type charNum;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _angle_type;
  _angle_type angle;



  enum {
    SUCCESS = 0,
    ERROR = 1,
    TIMEOUT = 2,
    NOT_DETECTED = 3,
    NOT_SUPPORT = 4,
  };


  typedef boost::shared_ptr< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct detectobjectionSrvResponse_

typedef ::probot_ocr::detectobjectionSrvResponse_<std::allocator<void> > detectobjectionSrvResponse;

typedef boost::shared_ptr< ::probot_ocr::detectobjectionSrvResponse > detectobjectionSrvResponsePtr;
typedef boost::shared_ptr< ::probot_ocr::detectobjectionSrvResponse const> detectobjectionSrvResponseConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_ocr

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39d54745614215fdcd7bbd923f88c1ca";
  }

  static const char* value(const ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39d54745614215fdULL;
  static const uint64_t static_value2 = 0xcd7bbd923f88c1caULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_ocr/detectobjectionSrvResponse";
  }

  static const char* value(const ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
int32 SUCCESS        = 0\n\
int32 ERROR          = 1\n\
int32 TIMEOUT        = 2\n\
int32 NOT_DETECTED   = 3\n\
int32 NOT_SUPPORT    = 4\n\
\n\
\n\
int32 result\n\
\n\
geometry_msgs/Pose[] charObjList\n\
string[] charName\n\
string[] charNum\n\
float64[] angle\n\
\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.charObjList);
      stream.next(m.charName);
      stream.next(m.charNum);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct detectobjectionSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_ocr::detectobjectionSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "charObjList[]" << std::endl;
    for (size_t i = 0; i < v.charObjList.size(); ++i)
    {
      s << indent << "  charObjList[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.charObjList[i]);
    }
    s << indent << "charName[]" << std::endl;
    for (size_t i = 0; i < v.charName.size(); ++i)
    {
      s << indent << "  charName[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.charName[i]);
    }
    s << indent << "charNum[]" << std::endl;
    for (size_t i = 0; i < v.charNum.size(); ++i)
    {
      s << indent << "  charNum[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.charNum[i]);
    }
    s << indent << "angle[]" << std::endl;
    for (size_t i = 0; i < v.angle.size(); ++i)
    {
      s << indent << "  angle[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_OCR_MESSAGE_DETECTOBJECTIONSRVRESPONSE_H
