// Generated by gencpp from file probot_detect/detectobjectionSrv.msg
// DO NOT EDIT!


#ifndef PROBOT_DETECT_MESSAGE_DETECTOBJECTIONSRV_H
#define PROBOT_DETECT_MESSAGE_DETECTOBJECTIONSRV_H

#include <ros/service_traits.h>


#include <probot_detect/detectobjectionSrvRequest.h>
#include <probot_detect/detectobjectionSrvResponse.h>


namespace probot_detect
{

struct detectobjectionSrv
{

typedef detectobjectionSrvRequest Request;
typedef detectobjectionSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct detectobjectionSrv
} // namespace probot_detect


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::probot_detect::detectobjectionSrv > {
  static const char* value()
  {
    return "629f585055d916a25d4222c22c18c0b5";
  }

  static const char* value(const ::probot_detect::detectobjectionSrv&) { return value(); }
};

template<>
struct DataType< ::probot_detect::detectobjectionSrv > {
  static const char* value()
  {
    return "probot_detect/detectobjectionSrv";
  }

  static const char* value(const ::probot_detect::detectobjectionSrv&) { return value(); }
};


// service_traits::MD5Sum< ::probot_detect::detectobjectionSrvRequest> should match 
// service_traits::MD5Sum< ::probot_detect::detectobjectionSrv > 
template<>
struct MD5Sum< ::probot_detect::detectobjectionSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::probot_detect::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_detect::detectobjectionSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_detect::detectobjectionSrvRequest> should match 
// service_traits::DataType< ::probot_detect::detectobjectionSrv > 
template<>
struct DataType< ::probot_detect::detectobjectionSrvRequest>
{
  static const char* value()
  {
    return DataType< ::probot_detect::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_detect::detectobjectionSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::probot_detect::detectobjectionSrvResponse> should match 
// service_traits::MD5Sum< ::probot_detect::detectobjectionSrv > 
template<>
struct MD5Sum< ::probot_detect::detectobjectionSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::probot_detect::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_detect::detectobjectionSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_detect::detectobjectionSrvResponse> should match 
// service_traits::DataType< ::probot_detect::detectobjectionSrv > 
template<>
struct DataType< ::probot_detect::detectobjectionSrvResponse>
{
  static const char* value()
  {
    return DataType< ::probot_detect::detectobjectionSrv >::value();
  }
  static const char* value(const ::probot_detect::detectobjectionSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROBOT_DETECT_MESSAGE_DETECTOBJECTIONSRV_H
