// Generated by gencpp from file probot_msgs/Config.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_CONFIG_H
#define PROBOT_MSGS_MESSAGE_CONFIG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace probot_msgs
{
template <class ContainerAllocator>
struct Config_
{
  typedef Config_<ContainerAllocator> Type;

  Config_()
    : controller_log_level(0)
    , init_with_all_zero_pos(false)
    , enable_joint_calibration(false)
    , seneor_position()
    , speed_to_sensor()
    , speed_to_zero()
    , pose_to_eef()
    , mask(0)  {
    }
  Config_(const ContainerAllocator& _alloc)
    : controller_log_level(0)
    , init_with_all_zero_pos(false)
    , enable_joint_calibration(false)
    , seneor_position(_alloc)
    , speed_to_sensor(_alloc)
    , speed_to_zero(_alloc)
    , pose_to_eef(_alloc)
    , mask(0)  {
  (void)_alloc;
    }



   typedef int8_t _controller_log_level_type;
  _controller_log_level_type controller_log_level;

   typedef uint8_t _init_with_all_zero_pos_type;
  _init_with_all_zero_pos_type init_with_all_zero_pos;

   typedef uint8_t _enable_joint_calibration_type;
  _enable_joint_calibration_type enable_joint_calibration;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _seneor_position_type;
  _seneor_position_type seneor_position;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _speed_to_sensor_type;
  _speed_to_sensor_type speed_to_sensor;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _speed_to_zero_type;
  _speed_to_zero_type speed_to_zero;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _pose_to_eef_type;
  _pose_to_eef_type pose_to_eef;

   typedef int32_t _mask_type;
  _mask_type mask;



  enum {
    MASK_LOGLEVEL = 1,
    MASK_ZERO_CALIBRATION = 2,
    MASK_TOOL_POSE = 4,
  };


  typedef boost::shared_ptr< ::probot_msgs::Config_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_msgs::Config_<ContainerAllocator> const> ConstPtr;

}; // struct Config_

typedef ::probot_msgs::Config_<std::allocator<void> > Config;

typedef boost::shared_ptr< ::probot_msgs::Config > ConfigPtr;
typedef boost::shared_ptr< ::probot_msgs::Config const> ConfigConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_msgs::Config_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_msgs::Config_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'probot_msgs': ['/home/akingse/catkin_ws/src/PROBOT_Anno/probot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::Config_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::Config_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::Config_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::Config_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::Config_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::Config_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_msgs::Config_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd76bb6e4c9a57426c629f8fe5205f36";
  }

  static const char* value(const ::probot_msgs::Config_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd76bb6e4c9a5742ULL;
  static const uint64_t static_value2 = 0x6c629f8fe5205f36ULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_msgs::Config_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_msgs/Config";
  }

  static const char* value(const ::probot_msgs::Config_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_msgs::Config_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The Config message contains system configuration data\n\
\n\
# The output log level for controller\n\
int8 controller_log_level\n\
bool init_with_all_zero_pos\n\
\n\
# The zero calibration parameters\n\
bool        enable_joint_calibration\n\
float32[]   seneor_position\n\
float32[]   speed_to_sensor\n\
float32[]   speed_to_zero\n\
\n\
# The tool's relative pose to end-effector(tool0)\n\
# This is used to jog tool instead of end-effector\n\
# If it is to jog end-effector, set pose_to_eef to 0, that is (0,0,0)(0,0,0,1)\n\
geometry_msgs/Pose[] pose_to_eef\n\
\n\
# The bit-map mask of valid fields which this message contains\n\
int32 mask\n\
\n\
int32 MASK_LOGLEVEL          = 1\n\
int32 MASK_ZERO_CALIBRATION  = 2\n\
int32 MASK_TOOL_POSE         = 4\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::probot_msgs::Config_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_msgs::Config_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller_log_level);
      stream.next(m.init_with_all_zero_pos);
      stream.next(m.enable_joint_calibration);
      stream.next(m.seneor_position);
      stream.next(m.speed_to_sensor);
      stream.next(m.speed_to_zero);
      stream.next(m.pose_to_eef);
      stream.next(m.mask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Config_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_msgs::Config_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_msgs::Config_<ContainerAllocator>& v)
  {
    s << indent << "controller_log_level: ";
    Printer<int8_t>::stream(s, indent + "  ", v.controller_log_level);
    s << indent << "init_with_all_zero_pos: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.init_with_all_zero_pos);
    s << indent << "enable_joint_calibration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_joint_calibration);
    s << indent << "seneor_position[]" << std::endl;
    for (size_t i = 0; i < v.seneor_position.size(); ++i)
    {
      s << indent << "  seneor_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.seneor_position[i]);
    }
    s << indent << "speed_to_sensor[]" << std::endl;
    for (size_t i = 0; i < v.speed_to_sensor.size(); ++i)
    {
      s << indent << "  speed_to_sensor[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.speed_to_sensor[i]);
    }
    s << indent << "speed_to_zero[]" << std::endl;
    for (size_t i = 0; i < v.speed_to_zero.size(); ++i)
    {
      s << indent << "  speed_to_zero[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.speed_to_zero[i]);
    }
    s << indent << "pose_to_eef[]" << std::endl;
    for (size_t i = 0; i < v.pose_to_eef.size(); ++i)
    {
      s << indent << "  pose_to_eef[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.pose_to_eef[i]);
    }
    s << indent << "mask: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_CONFIG_H
