// Generated by gencpp from file probot_msgs/HeartbeatSrv.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_HEARTBEATSRV_H
#define PROBOT_MSGS_MESSAGE_HEARTBEATSRV_H

#include <ros/service_traits.h>


#include <probot_msgs/HeartbeatSrvRequest.h>
#include <probot_msgs/HeartbeatSrvResponse.h>


namespace probot_msgs
{

struct HeartbeatSrv
{

typedef HeartbeatSrvRequest Request;
typedef HeartbeatSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HeartbeatSrv
} // namespace probot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::probot_msgs::HeartbeatSrv > {
  static const char* value()
  {
    return "98991985d4cdd4fbc58ba5a8e9c60574";
  }

  static const char* value(const ::probot_msgs::HeartbeatSrv&) { return value(); }
};

template<>
struct DataType< ::probot_msgs::HeartbeatSrv > {
  static const char* value()
  {
    return "probot_msgs/HeartbeatSrv";
  }

  static const char* value(const ::probot_msgs::HeartbeatSrv&) { return value(); }
};


// service_traits::MD5Sum< ::probot_msgs::HeartbeatSrvRequest> should match 
// service_traits::MD5Sum< ::probot_msgs::HeartbeatSrv > 
template<>
struct MD5Sum< ::probot_msgs::HeartbeatSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::probot_msgs::HeartbeatSrv >::value();
  }
  static const char* value(const ::probot_msgs::HeartbeatSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_msgs::HeartbeatSrvRequest> should match 
// service_traits::DataType< ::probot_msgs::HeartbeatSrv > 
template<>
struct DataType< ::probot_msgs::HeartbeatSrvRequest>
{
  static const char* value()
  {
    return DataType< ::probot_msgs::HeartbeatSrv >::value();
  }
  static const char* value(const ::probot_msgs::HeartbeatSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::probot_msgs::HeartbeatSrvResponse> should match 
// service_traits::MD5Sum< ::probot_msgs::HeartbeatSrv > 
template<>
struct MD5Sum< ::probot_msgs::HeartbeatSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::probot_msgs::HeartbeatSrv >::value();
  }
  static const char* value(const ::probot_msgs::HeartbeatSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::probot_msgs::HeartbeatSrvResponse> should match 
// service_traits::DataType< ::probot_msgs::HeartbeatSrv > 
template<>
struct DataType< ::probot_msgs::HeartbeatSrvResponse>
{
  static const char* value()
  {
    return DataType< ::probot_msgs::HeartbeatSrv >::value();
  }
  static const char* value(const ::probot_msgs::HeartbeatSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_HEARTBEATSRV_H
