// Generated by gencpp from file probot_msgs/RefreshPointsSrvResponse.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_REFRESHPOINTSSRVRESPONSE_H
#define PROBOT_MSGS_MESSAGE_REFRESHPOINTSSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <probot_msgs/InterfaceReturnCode.h>
#include <probot_msgs/PredefinedPointList.h>

namespace probot_msgs
{
template <class ContainerAllocator>
struct RefreshPointsSrvResponse_
{
  typedef RefreshPointsSrvResponse_<ContainerAllocator> Type;

  RefreshPointsSrvResponse_()
    : code()
    , pointListFeedback()  {
    }
  RefreshPointsSrvResponse_(const ContainerAllocator& _alloc)
    : code(_alloc)
    , pointListFeedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::probot_msgs::InterfaceReturnCode_<ContainerAllocator>  _code_type;
  _code_type code;

   typedef  ::probot_msgs::PredefinedPointList_<ContainerAllocator>  _pointListFeedback_type;
  _pointListFeedback_type pointListFeedback;





  typedef boost::shared_ptr< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RefreshPointsSrvResponse_

typedef ::probot_msgs::RefreshPointsSrvResponse_<std::allocator<void> > RefreshPointsSrvResponse;

typedef boost::shared_ptr< ::probot_msgs::RefreshPointsSrvResponse > RefreshPointsSrvResponsePtr;
typedef boost::shared_ptr< ::probot_msgs::RefreshPointsSrvResponse const> RefreshPointsSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'probot_msgs': ['/home/akingse/catkin_ws/src/PROBOT_Anno/probot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dfe497cd116d5e2b046e3b50c422dff";
  }

  static const char* value(const ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dfe497cd116d5e2ULL;
  static const uint64_t static_value2 = 0xb046e3b50c422dffULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_msgs/RefreshPointsSrvResponse";
  }

  static const char* value(const ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_msgs/InterfaceReturnCode code\n\
probot_msgs/PredefinedPointList pointListFeedback\n\
\n\
\n\
================================================================================\n\
MSG: probot_msgs/InterfaceReturnCode\n\
# App Interface return codes for requests.  All App Interface service\n\
# replies are required to have a return code indicating success or failure\n\
# Specific return codes for different failure should be negative.\n\
int8 val\n\
\n\
int8 SUCCESS = 1\n\
int8 FAILURE = -1\n\
================================================================================\n\
MSG: probot_msgs/PredefinedPointList\n\
# The predefined points list message contains all the pre-defined points\n\
\n\
PredefinedPoint[] points\n\
\n\
================================================================================\n\
MSG: probot_msgs/PredefinedPoint\n\
# The Predefined message contains the information of a pre-defined point on rviz\n\
\n\
string name\n\
geometry_msgs/Pose pose\n\
float64[] joints\n\
uint32 digitalOutput\n\
uint32 relayOutput\n\
float64 pointDelayBeforeExecute\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
      stream.next(m.pointListFeedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RefreshPointsSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_msgs::RefreshPointsSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    s << std::endl;
    Printer< ::probot_msgs::InterfaceReturnCode_<ContainerAllocator> >::stream(s, indent + "  ", v.code);
    s << indent << "pointListFeedback: ";
    s << std::endl;
    Printer< ::probot_msgs::PredefinedPointList_<ContainerAllocator> >::stream(s, indent + "  ", v.pointListFeedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_REFRESHPOINTSSRVRESPONSE_H
