// Generated by gencpp from file probot_msgs/SetOutputIO.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_SETOUTPUTIO_H
#define PROBOT_MSGS_MESSAGE_SETOUTPUTIO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_msgs
{
template <class ContainerAllocator>
struct SetOutputIO_
{
  typedef SetOutputIO_<ContainerAllocator> Type;

  SetOutputIO_()
    : type(0)
    , mask(0)
    , status(0)  {
    }
  SetOutputIO_(const ContainerAllocator& _alloc)
    : type(0)
    , mask(0)
    , status(0)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef uint32_t _mask_type;
  _mask_type mask;

   typedef uint32_t _status_type;
  _status_type status;



  enum {
    TYPE_DIGITAL = 0,
    TYPE_RELAY = 1,
    IO_OFF = 0,
    IO_ON = 1,
  };


  typedef boost::shared_ptr< ::probot_msgs::SetOutputIO_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_msgs::SetOutputIO_<ContainerAllocator> const> ConstPtr;

}; // struct SetOutputIO_

typedef ::probot_msgs::SetOutputIO_<std::allocator<void> > SetOutputIO;

typedef boost::shared_ptr< ::probot_msgs::SetOutputIO > SetOutputIOPtr;
typedef boost::shared_ptr< ::probot_msgs::SetOutputIO const> SetOutputIOConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_msgs::SetOutputIO_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_msgs::SetOutputIO_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'probot_msgs': ['/home/akingse/catkin_ws/src/PROBOT_Anno/probot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::SetOutputIO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::SetOutputIO_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::SetOutputIO_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6449e032301ef457b18691c68ae57e69";
  }

  static const char* value(const ::probot_msgs::SetOutputIO_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6449e032301ef457ULL;
  static const uint64_t static_value2 = 0xb18691c68ae57e69ULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_msgs/SetOutputIO";
  }

  static const char* value(const ::probot_msgs::SetOutputIO_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 type\n\
uint32 mask\n\
uint32 status\n\
\n\
int8 TYPE_DIGITAL  = 0\n\
int8 TYPE_RELAY    = 1\n\
\n\
int8 IO_OFF  = 0\n\
int8 IO_ON = 1\n\
";
  }

  static const char* value(const ::probot_msgs::SetOutputIO_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.mask);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetOutputIO_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_msgs::SetOutputIO_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_msgs::SetOutputIO_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "mask: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mask);
    s << indent << "status: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_SETOUTPUTIO_H
