// Generated by gencpp from file probot_msgs/SFUVersionNum.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_SFUVERSIONNUM_H
#define PROBOT_MSGS_MESSAGE_SFUVERSIONNUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_msgs
{
template <class ContainerAllocator>
struct SFUVersionNum_
{
  typedef SFUVersionNum_<ContainerAllocator> Type;

  SFUVersionNum_()
    : version()  {
    }
  SFUVersionNum_(const ContainerAllocator& _alloc)
    : version(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _version_type;
  _version_type version;





  typedef boost::shared_ptr< ::probot_msgs::SFUVersionNum_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_msgs::SFUVersionNum_<ContainerAllocator> const> ConstPtr;

}; // struct SFUVersionNum_

typedef ::probot_msgs::SFUVersionNum_<std::allocator<void> > SFUVersionNum;

typedef boost::shared_ptr< ::probot_msgs::SFUVersionNum > SFUVersionNumPtr;
typedef boost::shared_ptr< ::probot_msgs::SFUVersionNum const> SFUVersionNumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_msgs::SFUVersionNum_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'probot_msgs': ['/home/akingse/catkin_ws/src/PROBOT_Anno/probot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::SFUVersionNum_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::SFUVersionNum_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::SFUVersionNum_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a6f3c569a7ebe01c997148cb8f0f453";
  }

  static const char* value(const ::probot_msgs::SFUVersionNum_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a6f3c569a7ebe01ULL;
  static const uint64_t static_value2 = 0xc997148cb8f0f453ULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_msgs/SFUVersionNum";
  }

  static const char* value(const ::probot_msgs::SFUVersionNum_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string version\n\
";
  }

  static const char* value(const ::probot_msgs::SFUVersionNum_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SFUVersionNum_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_msgs::SFUVersionNum_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_msgs::SFUVersionNum_<ContainerAllocator>& v)
  {
    s << indent << "version: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_SFUVERSIONNUM_H
